config/routes.rb
Rails.application.routes.draw do
  
  scope '(:locale)' do  
    resources :sheep
    root 'sheep#index'
  end
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sheep.rb
class Sheep < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
protect_from_forgery with: :exception  
before_action :set_i18n_locale_from_params








  protected
    def set_i18n_locale_from_params 
      if params[:locale]
        if I18n.available_locales.map(&:to_s).include?(params[:locale]) 
          I18n.locale = params[:locale]
        else
            flash.now[:notice] =
              "#{params[:locale]} translation not available"
            logger.error flash.now[:notice] 
        end
      end
    end

end

app/controllers/sheep_controller.rb
class SheepController < ApplicationController
  before_action :set_sheep, only: [:show, :edit, :update, :destroy]

  # GET /sheep
  # GET /sheep.json
  def index
    @sheep = Sheep.all
  end

  # GET /sheep/1
  # GET /sheep/1.json
  def show
  end

  # GET /sheep/new
  def new
    @sheep = Sheep.new
  end

  # GET /sheep/1/edit
  def edit
  end

  # POST /sheep
  # POST /sheep.json
  def create
    @sheep = Sheep.new(sheep_params)

    respond_to do |format|
      if @sheep.save
        format.html { redirect_to @sheep, notice: 'Sheep was successfully created.' }
        format.json { render :show, status: :created, location: @sheep }
      else
        format.html { render :new }
        format.json { render json: @sheep.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sheep/1
  # PATCH/PUT /sheep/1.json
  def update
    respond_to do |format|
      if @sheep.update(sheep_params)
        format.html { redirect_to @sheep, notice: 'Sheep was successfully updated.' }
        format.json { render :show, status: :ok, location: @sheep }
      else
        format.html { render :edit }
        format.json { render json: @sheep.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sheep/1
  # DELETE /sheep/1.json
  def destroy
    @sheep.destroy
    respond_to do |format|
      format.html { redirect_to sheep_index_url, notice: 'Sheep was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sheep
      @sheep = Sheep.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sheep_params
      params.require(:sheep).permit(:description, :status, :priority)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sheep_helper.rb
module SheepHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('.title_html') %></title>
    <%= csrf_meta_tags %>
	
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sheep/_form.html.erb
<%= form_with(model: sheep, local: true) do |form| %>
  <% if sheep.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sheep.errors.count, "error") %> prohibited this sheep from being saved:</h2>

      <ul>
      <% sheep.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description, t('.description') %>
    <%= form.trix_editor :description, id: :sheep_description %>
  </div>

  <div class="field">
    <%= form.label :status, t('.status') %>
    <%= form.text_field :status, id: :sheep_status %>
  </div>

  <div class="field">
    <%= form.label :priority %>
    <%= form.text_field :priority, id: :sheep_priority %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
	

	
<% end %>

app/views/sheep/edit.html.erb
<h1>Editing Sheep</h1>

<%= render 'form', sheep: @sheep %>

<%= link_to 'Show', @sheep %> |
<%= link_to 'Back', sheep_index_path %>

app/views/sheep/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('.heading') %></h1>

<table>
  <thead>
    <tr>
      <th><%= t('.description') %></th>
      <th><%= t('.status') %></th>
      <th><%= t('.priority') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sheep.each do |sheep| %>
      <tr>
        <td><%= sheep.description.html_safe %></td>
        <td><%= sheep.status %></td>
        <td><%= sheep.priority %></td>
        <td><%= link_to 'Show', sheep %></td>
        <td><%= link_to 'Edit', edit_sheep_path(sheep) %></td>
        <td><%= link_to 'Destroy', sheep, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sheep', new_sheep_path %>

app/views/sheep/new.html.erb
<h1>New Sheep</h1>

<%= render 'form', sheep: @sheep %>

<%= link_to 'Back', sheep_index_path %>

app/views/sheep/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @sheep.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @sheep.status %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @sheep.priority %>
</p>

<%= link_to 'Edit', edit_sheep_path(@sheep) %> |
<%= link_to 'Back', sheep_index_path %>